<?php
/** @var CustomView $block */

use PreferencesExamples\Block\CustomView;
use Magento\Framework\App\ObjectManager;
use Magento\Framework\Pricing\Helper\Data;

$_product = $block->getProduct();


$objectManager = ObjectManager::getInstance();
/** @var Data $priceHelper */
$priceHelper = $objectManager->get(Data::class);


$finalPrice = $_product->getFinalPrice();
?>

<h1><?= $block->escapeHtml($_product->getName()) ?></h1>
<p>Product price: <?= $priceHelper->currency($finalPrice) ?></p>
